# Generated by Django 5.0.7 on 2024-08-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
    ]
