# Generated by Django 5.0.7 on 2024-08-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_execo'),
    ]

    operations = [
        migrations.AddField(
            model_name='execo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
