# Generated by Django 5.0.7 on 2024-09-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports & Recreation'), ('Inductions', 'Inductions'), ('Awards', 'Award Nites'), ('Courtesy', 'Courtesy Visits'), ('Retreats', 'Club Retreats'), ('Burials', 'Burials'), ('Monthly Meetings', 'Monthly Meetings')], max_length=100),
        ),
    ]
