# Generated by Django 5.0.7 on 2024-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sports & Recreation', 'Sports & Recreation'), ('Inductions', 'Inductions'), ('Award Nites', 'Award Nites'), ('Courtesy Visits', 'Courtesy Visits'), ('Club Retreats', 'Club Retreats'), ('Burials', 'Burials'), ('Monthly Meetings', 'Monthly Meetings')], max_length=100),
        ),
    ]
