# Generated by Django 5.0.7 on 2024-08-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_image_category_alter_image_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
