# Generated by Django 5.0.7 on 2024-09-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_event_up'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_up',
            new_name='Event_update',
        ),
    ]
